<a href="https://colab.research.google.com/github/Anan-punathil/entri_dsml_test/blob/main/SVM_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/alexjolly28/entri_DSML/main/resources/emails.csv

--2024-05-06 13:07:54--  https://raw.githubusercontent.com/alexjolly28/entri_DSML/main/resources/emails.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31243156 (30M) [text/plain]
Saving to: ‘emails.csv’

emails.csv          100%[===================>]  29.79M   165MB/s    in 0.2s    

2024-05-06 13:07:55 (165 MB/s) - ‘emails.csv’ saved [31243156/31243156]



# importing libraries

In [2]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as sm

# loading data set

In [3]:
dataset=pd.read_csv('/content/emails.csv')
dataset.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [4]:
dataset.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [5]:
dataset[dataset.isnull().any(axis=1)]

Empty DataFrame
Columns: [Email No., the, to, ect, and, for, of, a, you, hou, in, on, is, this, enron, i, be, that, will, have, with, your, at, we, s, are, it, by, com, as, from, gas, or, not, me, deal, if, meter, hpl, please, re, e, any, our, corp, can, d, all, has, was, know, need, an, forwarded, new, t, may, up, j, mmbtu, should, do, am, get, out, see, no, there, price, daren, but, been, company, l, these, let, so, would, m, into, xls, farmer, attached, us, information, they, message, day, time, my, one, what, only, http, th, volume, mail, contract, which, month, ...]
Index: []

[0 rows x 3002 columns]

In [6]:
categorical = [var for var in dataset.columns if dataset[var].dtype=='O']
numerical = [var for var in dataset.columns if dataset[var].dtype!='O']

In [7]:
print('There are {} categorical variables : \n'.format(len(categorical)), categorical)

There are 1 categorical variables : 
 ['Email No.']


In [8]:
# check for cardinality in categorical variables
for var in categorical:
    print(var, ' contains ', len(dataset[var].unique()), ' labels')

Email No.  contains  5172  labels


In [9]:
# view summary statistics in numerical variables to check for outliers
print(round(dataset[numerical].describe()),2)

          the      to     ect     and     for      of       a     you     hou  \
count  5172.0  5172.0  5172.0  5172.0  5172.0  5172.0  5172.0  5172.0  5172.0   
mean      7.0     6.0     5.0     3.0     3.0     3.0    56.0     2.0     2.0   
std      12.0    10.0    14.0     6.0     5.0     6.0    88.0     4.0     7.0   
min       0.0     0.0     1.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       0.0     1.0     1.0     0.0     1.0     0.0    12.0     0.0     0.0   
50%       3.0     3.0     1.0     1.0     2.0     1.0    28.0     1.0     0.0   
75%       8.0     7.0     4.0     3.0     4.0     2.0    62.0     3.0     1.0   
max     210.0   132.0   344.0    89.0    47.0    77.0  1898.0    70.0   167.0   

           in  ...  connevey     jay  valued     lay  infrastructure  \
count  5172.0  ...    5172.0  5172.0  5172.0  5172.0          5172.0   
mean     11.0  ...       0.0     0.0     0.0     0.0             0.0   
std      19.0  ...       0.0     0.0     0.0     1.0  

# data preprocessing

In [10]:
# use LabelEncoder to replace purchased (dependent variable) with 0 and 1
from sklearn.preprocessing import LabelEncoder
dataset['Email No.']= LabelEncoder().fit_transform(dataset['Email No.'])
dataset.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0          0    0   0    1    0    0   0    2    0    0  ...         0    0   
1       1111    8  13   24    6    6   2  102    1   27  ...         0    0   
2       2222    0   0    1    0    0   0    8    0    0  ...         0    0   
3       3333    0   5   22    0    5   1   51    2   10  ...         0    0   
4       4444    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [11]:
y = dataset['Prediction']
x = dataset.drop(['Prediction'], axis=1)

# splitting data set into train test data

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

# build model

In [14]:
from sklearn.svm import SVC
svr_lin = SVC(kernel='linear', C=100, gamma='auto')
svr_lin.fit(x_train,y_train)
y_pred_lin= svr_lin.predict(x_test)

In [15]:
svr_rbf = SVC(kernel='rbf', C=100, gamma=0.1)
svr_rbf.fit(x_train,y_train)
y_pred_rbf= svr_rbf.predict(x_test)

In [16]:
# poly kernel type to be used in the algorithm
svr_poly = SVC(kernel='poly', C=100, gamma='auto', degree=3,  coef0=1)
svr_poly.fit(x_train,y_train)
y_pred_poly= svr_poly.predict(x_test)

In [17]:
# sigmoid kernel type to be used in the algorithm
svr_sig = SVC(kernel='sigmoid', C=1, gamma='auto',  coef0=1)
svr_sig.fit(x_train,y_train)
y_pred_sig= svr_sig.predict(x_test)

# evaluating the model

evaluation of linear model

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, average_precision_score
cm = confusion_matrix(y_test,y_pred_lin)
print(cm)

[[1057   54]
 [  38  403]]


In [19]:
cr = classification_report(y_test,y_pred_lin)
print(cr)

              precision    recall  f1-score   support

           0       0.97      0.95      0.96      1111
           1       0.88      0.91      0.90       441

    accuracy                           0.94      1552
   macro avg       0.92      0.93      0.93      1552
weighted avg       0.94      0.94      0.94      1552



In [20]:
accuracy_score(y_test,y_pred_lin)

0.9407216494845361

In [21]:
average_precision_score(y_test,y_pred_lin)

0.8303365632536637

evaluation of rbf model

In [22]:
cm = confusion_matrix(y_test,y_pred_rbf)
print(cm)

[[1108    3]
 [ 412   29]]


In [23]:
cr = classification_report(y_test,y_pred_rbf)
print(cr)

              precision    recall  f1-score   support

           0       0.73      1.00      0.84      1111
           1       0.91      0.07      0.12       441

    accuracy                           0.73      1552
   macro avg       0.82      0.53      0.48      1552
weighted avg       0.78      0.73      0.64      1552



In [24]:
accuracy_score(y_test,y_pred_rbf)

0.7326030927835051

In [25]:
average_precision_score(y_test,y_pred_rbf)

0.32505858872758725

evaluation of poly model

In [26]:
cm = confusion_matrix(y_test,y_pred_poly)
print(cm)

[[1067   44]
 [  44  397]]


In [27]:
cr = classification_report(y_test,y_pred_poly)
print(cr)

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      1111
           1       0.90      0.90      0.90       441

    accuracy                           0.94      1552
   macro avg       0.93      0.93      0.93      1552
weighted avg       0.94      0.94      0.94      1552



In [28]:
accuracy_score(y_test,y_pred_poly)

0.9432989690721649

In [29]:
average_precision_score(y_test,y_pred_poly)

0.8387587301481284

evaluation of sigmoid model

In [30]:
cm = confusion_matrix(y_test,y_pred_sig)
print(cm)

[[1058   53]
 [ 158  283]]


In [31]:
cr = classification_report(y_test,y_pred_sig)
print(cr)

              precision    recall  f1-score   support

           0       0.87      0.95      0.91      1111
           1       0.84      0.64      0.73       441

    accuracy                           0.86      1552
   macro avg       0.86      0.80      0.82      1552
weighted avg       0.86      0.86      0.86      1552



In [32]:
accuracy_score(y_test,y_pred_sig)

0.8640463917525774

In [33]:
average_precision_score(y_test,y_pred_sig)

0.6423032598737416